param([Parameter(Position=0,Mandatory=$true)][ValidateSet('status','new','validate','rank')][string]$Command,[string]$Title,[string]$Source,[ValidateSet('serving','kernel','memory','compression','distributed','hardware-economics','other')][string]$Topic='other',[string]$Path,[ValidateRange(1,200)][int]$Limit=20)
$ErrorActionPreference='Stop'
$vaultRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$radarRoot=Join-Path $vaultRoot '3_AI情报日历\Inbox\InferenceRadar'
$templatePath=Join-Path $vaultRoot '0_Codex工作台\Templates\AI推理信号卡模板.md'
function Field($content,$name){$m=[regex]::Match($content,'(?m)^'+[regex]::Escape($name)+':\s*"?([^"\r\n]*)"?\s*$');if($m.Success){$m.Groups[1].Value.Trim()}else{''}}
function Cards {Get-ChildItem -LiteralPath $radarRoot -File -Filter '*.md' -Recurse|Where-Object Name -ne 'README.md'}
function Inspect($target){$content=Get-Content -Raw -LiteralPath $target;$issues=@();foreach($field in @('type','date','discovered','source_type','primary_source','topic','status','evidence_score','overall_score','confidence','decision')){if([string]::IsNullOrWhiteSpace((Field $content $field))){$issues+="Missing field: $field"}};foreach($section in @('## 事件','## 一手证据','## 定量结果','## 适用边界','## Codex 判断','## 下一步')){if(-not $content.Contains($section)){$issues+="Missing section: $section"}};if((Field $content 'primary_source') -notmatch '^https://'){$issues+='primary_source must be an HTTPS original source.'};$e=0;[void][int]::TryParse((Field $content 'evidence_score'),[ref]$e);if($e -lt 2 -and $content -match '显著提升|重大突破|行业领先|大幅降低'){$issues+='Strong claim used with evidence_score below 2.'};[pscustomobject]@{Valid=($issues.Count -eq 0);Issues=$issues}}
switch($Command){
'status'{$cards=@(Cards);$valid=0;foreach($card in $cards){if((Inspect $card.FullName).Valid){$valid++}};[pscustomobject]@{Vault=$vaultRoot;Cards=$cards.Count;Valid=$valid;Inbox=$radarRoot}|Format-List}
'new'{if(!$Title){throw 'new requires -Title'};if($Source -notmatch '^https://'){throw 'new requires an HTTPS original -Source'};$folder=Join-Path $radarRoot (Get-Date -Format 'yyyy-MM');New-Item -ItemType Directory -Force -Path $folder|Out-Null;$safe=$Title -replace '[\\/:*?"<>|]','_';$target=Join-Path $folder ((Get-Date -Format 'yyyy-MM-dd')+'_'+$safe+'.md');if(Test-Path $target){throw 'Signal already exists'};$content=Get-Content -Raw $templatePath;$content=$content.Replace('{{date}}',(Get-Date -Format 'yyyy-MM-dd')).Replace('{{timestamp}}',(Get-Date).ToString('s')).Replace('{{source}}',$Source).Replace('{{title}}',$Title).Replace('{{topic}}',$Topic);[IO.File]::WriteAllText($target,$content,[Text.UTF8Encoding]::new($false));$target}
'validate'{if(!$Path){throw 'validate requires -Path'};$target=if([IO.Path]::IsPathRooted($Path)){$Path}else{Join-Path $vaultRoot $Path};$target=(Resolve-Path $target).Path;if(-not $target.StartsWith($vaultRoot,[StringComparison]::OrdinalIgnoreCase)){throw 'Path outside vault'};$result=Inspect $target;if($result.Valid){'OK'}else{$result.Issues|ForEach-Object{Write-Error $_ -ErrorAction Continue};exit 1}}
'rank'{$rows=foreach($card in Cards){$content=Get-Content -Raw $card.FullName;[pscustomobject]@{Score=[double](Field $content 'overall_score');Evidence=[int](Field $content 'evidence_score');Topic=Field $content 'topic';Status=Field $content 'status';Path=$card.FullName.Substring($vaultRoot.Length+1)}};$rows|Sort-Object Score -Descending|Select-Object -First $Limit|Format-Table -AutoSize}}